version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "[%(asctime)s] #%(levelname)-8s %(filename)s:%(lineno)d - %(name)s - %(message)s"
  color:
    (): src.core.logging.ColoredFormatter
    format: "[%(asctime)s] #%(levelname)-8s %(filename)s:%(lineno)d - %(name)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: color
    stream: ext://sys.stdout
loggers:
  root:
    level: INFO
    handlers:
      - console